services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    container_name: vuejs-docs-app
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: vuejs-docs-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - app-network
    volumes:
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro

networks:
  app-network:
    driver: bridge 